//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MultiSigExample.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MultiSigExample.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///	{
        ///		&quot;constant&quot;: false,
        ///		&quot;inputs&quot;: [
        ///			{
        ///				&quot;name&quot;: &quot;newValue&quot;,
        ///				&quot;type&quot;: &quot;uint256&quot;
        ///			}
        ///		],
        ///		&quot;name&quot;: &quot;Execute&quot;,
        ///		&quot;outputs&quot;: [],
        ///		&quot;payable&quot;: false,
        ///		&quot;stateMutability&quot;: &quot;nonpayable&quot;,
        ///		&quot;type&quot;: &quot;function&quot;
        ///	},
        ///	{
        ///		&quot;anonymous&quot;: false,
        ///		&quot;inputs&quot;: [
        ///			{
        ///				&quot;indexed&quot;: false,
        ///				&quot;name&quot;: &quot;_from&quot;,
        ///				&quot;type&quot;: &quot;address&quot;
        ///			},
        ///			{
        ///				&quot;indexed&quot;: false,
        ///				&quot;name&quot;: &quot;_value&quot;,
        ///				&quot;type&quot;: &quot;uint256&quot;
        ///			}
        ///		],
        ///		&quot;name&quot;: &quot;execution&quot;,
        ///		&quot;type&quot;: &quot;event&quot;
        ///	},
        ///	{
        ///		&quot;constant&quot;: tr [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ExampleContractABI {
            get {
                return ResourceManager.GetString("ExampleContractABI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///	{
        ///		&quot;constant&quot;: false,
        ///		&quot;inputs&quot;: [
        ///			{
        ///				&quot;name&quot;: &quot;_owner&quot;,
        ///				&quot;type&quot;: &quot;address&quot;
        ///			}
        ///		],
        ///		&quot;name&quot;: &quot;removeOwner&quot;,
        ///		&quot;outputs&quot;: [],
        ///		&quot;payable&quot;: false,
        ///		&quot;stateMutability&quot;: &quot;nonpayable&quot;,
        ///		&quot;type&quot;: &quot;function&quot;
        ///	},
        ///	{
        ///		&quot;constant&quot;: false,
        ///		&quot;inputs&quot;: [
        ///			{
        ///				&quot;name&quot;: &quot;_addr&quot;,
        ///				&quot;type&quot;: &quot;address&quot;
        ///			}
        ///		],
        ///		&quot;name&quot;: &quot;isOwner&quot;,
        ///		&quot;outputs&quot;: [
        ///			{
        ///				&quot;name&quot;: &quot;&quot;,
        ///				&quot;type&quot;: &quot;bool&quot;
        ///			}
        ///		],
        ///		&quot;payable&quot;: false,
        ///		&quot;stateMutability&quot;: &quot;nonpayable&quot;,
        ///		&quot;type&quot;: &quot;function&quot;
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MultiSigABI {
            get {
                return ResourceManager.GetString("MultiSigABI", resourceCulture);
            }
        }
    }
}
